### ISSUE TITLE
DKMS build fails on latest Fedora kernel

### ISSUE THREAD

**Issue by etem** [Grawp/rtl8812au_rtl8821au#44]
Hello, 

The driver was working perfectly fine for last 2 months. 
But after an upgrade to the latest kernel on Fedora 25 today it fails on build : 

`[root@localhost rtldriver] # dkms install -m 8812au -v v4.3.20_16317.20160108

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' all KVER=4.11.3-200.fc25.x86_64...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.11.3-200.fc25.x86_64 (x86_64)
Consult /var/lib/dkms/8812au/v4.3.20_16317.20160108/build/make.log for more information.
`

**Comment by etem** [comment]
And contents of the make.log file : 

`DKMS make.log for 8812au-v4.3.20_16317.20160108 for kernel 4.11.3-200.fc25.x86_64 (x86_64)
чт юни  1 22:02:00 EEST 2017
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.11.3-200.fc25.x86_64/build M=/var/lib/dkms/8812au/v4.3.20_16317.20160108/build  modules
make[1]: Entering directory '/usr/src/kernels/4.11.3-200.fc25.x86_64'
Makefile:923: "Cannot use CONFIG_STACK_VALIDATION, please install libelf-dev, libelf-devel or elfutils-libelf-devel"
  CC [M]  /var/lib/dkms/8812au/v4.3.20_16317.20160108/build/core/rtw_cmd.o
In file included from /var/lib/dkms/8812au/v4.3.20_16317.20160108/build/include/drv_types.h:32:0,
                 from /var/lib/dkms/8812au/v4.3.20_16317.20160108/build/core/rtw_cmd.c:22:
/var/lib/dkms/8812au/v4.3.20_16317.20160108/build/include/osdep_service.h: In function ‘thread_enter’:
/var/lib/dkms/8812au/v4.3.20_16317.20160108/build/include/osdep_service.h:343:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/var/lib/dkms/8812au/v4.3.20_16317.20160108/build/include/osdep_service.h: In function ‘flush_signals_thread’:
/var/lib/dkms/8812au/v4.3.20_16317.20160108/build/include/osdep_service.h:353:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/var/lib/dkms/8812au/v4.3.20_16317.20160108/build/include/osdep_service.h:355:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/var/lib/dkms/8812au/v4.3.20_16317.20160108/build/core/rtw_cmd.o' failed
make[2]: *** [/var/lib/dkms/8812au/v4.3.20_16317.20160108/build/core/rtw_cmd.o] Error 1
Makefile:1496: recipe for target '_module_/var/lib/dkms/8812au/v4.3.20_16317.20160108/build' failed
make[1]: *** [_module_/var/lib/dkms/8812au/v4.3.20_16317.20160108/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.11.3-200.fc25.x86_64'
Makefile:1670: recipe for target 'modules' failed
make: *** [modules] Error 2
`

**Comment by CGarces** [comment]
Maybe you need https://github.com/Grawp/rtl8812au_rtl8821au/pull/41

**Comment by etem** [comment]
Thank you!
Works perfectly with this patch.
